[package]
name = "neocities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
thiserror = "1.0.38"
tokio = { version = "1", features = ["full"] }
url = "2.3.1"
